        vector<int> ans;
        priority_queue<pair<int,int>, vector<pair<int, int>>, greater<pair<int, int>>> pq;
        sort(begin(task),end(task));
        int time=0,i=0;
        for(int i=0;i<task.size();i++)task[i].push_back(i);
    vector<int> getOrder(vector<vector<int>>& task) {
        while(i<task.size())
public:
        {
[
